import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import { getDatabase, ref, get, set, update, onValue, onDisconnect, remove, push, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js';

const firebaseConfig={apiKey:'AIzaSyAhQcvXPsAkc22WQmnLII17JUNnYj_oeKQ',authDomain:'skinners-bar-bingo.firebaseapp.com',databaseURL:'https://skinners-bar-bingo-default-rtdb.europe-west1.firebasedatabase.app',projectId:'skinners-bar-bingo',storageBucket:'skinners-bar-bingo.firebasestorage.app',messagingSenderId:'1033478065497',appId:'1:1033478065497:web:e7b4904fd9ef7afd171048'};
const db=getDatabase(initializeApp(firebaseConfig));
const $=id=>document.getElementById(id),views=['homeView','lobbyView','gameView'];
const state={isHost:false,roomCode:'',roomRef:null,unsubscribe:null,claimUnsub:null,myId:localStorage.getItem('skinnersPlayerId')||crypto.randomUUID(),myName:'',players:[],tickets:{},called:[],deck:[],phase:'home',autoTimer:null,sound:true,audioCtx:null,audioReady:false,marks:new Set(),mode:'classic',prizes:{line:25,'two-lines':50,'full-house':100},actions:[],wins:{},balances:{},noticeId:null,partyId:null,finishedId:null,chat:[],myLocalCoins:Number(localStorage.getItem('skinnersCoins')||0)};
localStorage.setItem('skinnersPlayerId',state.myId);

function showView(id){views.forEach(v=>$(v).classList.toggle('active',v===id));}
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2300);}
function cleanName(v){return(v||'Player').trim().replace(/[<>]/g,'').slice(0,18)||'Player';}
function cleanMessage(v){return(v||'').trim().replace(/[<>]/g,'').slice(0,180);}
function code(){return String(Math.floor(1000+Math.random()*9000));}
function shuffled(a){return[...a].sort(()=>Math.random()-.5);}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function roomPath(c){return ref(db,`rooms/${c}`);} function playerPath(c,id){return ref(db,`rooms/${c}/players/${id}`);}

function makeTicket(){const ranges=[[1,9],[10,19],[20,29],[30,39],[40,49],[50,59],[60,69],[70,79],[80,90]];for(let a=0;a<250;a++){const g=Array.from({length:3},()=>Array(9).fill(0)),cc=Array(9).fill(1);let rem=6;while(rem){const c=Math.floor(Math.random()*9);if(cc[c]<3){cc[c]++;rem--;}}const rs=[0,0,0];for(let c=0;c<9;c++){const rows=shuffled([0,1,2]).slice(0,cc[c]);rows.forEach(r=>rs[r]++);const nums=shuffled(Array.from({length:ranges[c][1]-ranges[c][0]+1},(_,i)=>ranges[c][0]+i)).slice(0,cc[c]).sort((x,y)=>x-y);rows.sort((x,y)=>x-y).forEach((r,i)=>g[r][c]=nums[i]);}if(rs.every(n=>n===5))return g;}return[[1,0,23,0,41,56,0,72,88],[0,12,28,34,0,59,63,0,90],[7,19,0,38,49,0,68,77,0]];}

function normaliseRoom(room={}){state.players=Object.entries(room.players||{}).map(([id,p])=>({id,...p}));state.tickets=room.tickets||{};state.called=Array.isArray(room.called)?room.called:[];state.deck=Array.isArray(room.deck)?room.deck:[];state.phase=room.phase||'lobby';state.mode=room.mode||'classic';state.prizes=room.prizes||state.prizes;state.actions=Array.isArray(room.actions)?room.actions:[];state.wins=room.wins||{};state.balances=room.balances||{};state.chat=Object.entries(room.chat||{}).map(([id,m])=>({id,...m})).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0)).slice(-50);
 if(room.notice?.id&&room.notice.id!==state.noticeId){state.noticeId=room.notice.id;if(!room.notice.target||room.notice.target===state.myId)showModal(room.notice.title,room.notice.message,room.notice.emoji||'🎉');}
 if(room.partyEvent?.id&&room.partyEvent.id!==state.partyId){state.partyId=room.partyEvent.id;showParty(room.partyEvent.number,room.partyEvent.action);}
 if(room.finished?.id&&room.finished.id!==state.finishedId){state.finishedId=room.finished.id;stopAuto();showModal('Congratulations!',`${room.finished.winnerName} has won the Full House and the game is now finished!`,'🏆');}
 showView(state.phase==='lobby'?'lobbyView':'gameView');render();}

function listenToRoom(){state.unsubscribe?.();state.roomRef=roomPath(state.roomCode);state.unsubscribe=onValue(state.roomRef,s=>{if(!s.exists()){showModal('Room closed','This room is no longer available.','📡');return;}normaliseRoom(s.val());},e=>{console.error(e);showModal('Connection problem','Firebase could not read this room. Check the database rules.','⚠️');});attachClaimListener();}
async function reserveRoom(){for(let i=0;i<20;i++){const c=code(),snap=await get(roomPath(c));if(!snap.exists())return c;}throw Error('Could not create a unique room code');}

async function createGame(){state.myName=cleanName($('hostName').value||'Michael');state.mode=$('gameMode').value;if(state.mode==='party'&&!$('adultConfirm').checked){$('createStatus').textContent='Please confirm the responsible-play notice first.';return;}state.prizes={line:+$('linePrize').value||0,'two-lines':+$('twoPrize').value||0,'full-house':+$('housePrize').value||0};state.actions=$('partyActions').value.split('\n').map(x=>x.trim()).filter(Boolean);$('confirmCreateBtn').disabled=true;$('createStatus').textContent='Creating online room…';try{state.roomCode=await reserveRoom();state.isHost=true;await set(roomPath(state.roomCode),{createdAt:Date.now(),hostId:state.myId,phase:'lobby',mode:state.mode,prizes:state.prizes,actions:state.actions,called:[],deck:[],tickets:{},wins:{},balances:{[state.myId]:state.myLocalCoins},players:{[state.myId]:{name:state.myName,creator:true,connected:true,lastSeen:Date.now()}}});await onDisconnect(playerPath(state.roomCode,state.myId)).update({connected:false,lastSeen:serverTimestamp()});listenToRoom();}catch(e){console.error(e);$('confirmCreateBtn').disabled=false;$('createStatus').textContent='Could not create the room. Check Firebase and try again.';}}
async function joinGame(){const n=cleanName($('joinName').value),c=$('roomCodeInput').value.trim();if(!/^\d{4}$/.test(c)){$('joinStatus').textContent='Enter the four-digit room code.';return;}$('joinGameBtn').disabled=true;$('joinStatus').textContent='Joining online room…';try{const snap=await get(roomPath(c));if(!snap.exists())throw Error('Room not found');const room=snap.val();state.myName=n;state.roomCode=c;state.isHost=room.hostId===state.myId;await update(roomPath(c),{[`players/${state.myId}`]:{name:n,creator:state.isHost,connected:true,lastSeen:Date.now()},[`balances/${state.myId}`]:room.balances?.[state.myId]??state.myLocalCoins});await onDisconnect(playerPath(c,state.myId)).update({connected:false,lastSeen:serverTimestamp()});listenToRoom();}catch(e){console.error(e);$('joinStatus').textContent='Room not found or Firebase connection failed.';$('joinGameBtn').disabled=false;}}

async function startGame(){if(!state.isHost)return;stopAuto();const tickets={};state.players.filter(p=>p.connected).forEach(p=>tickets[p.id]=makeTicket());state.marks.clear();await update(state.roomRef,{phase:'playing',tickets,called:[],deck:shuffled(Array.from({length:90},(_,i)=>i+1)),wins:{},notice:null,partyEvent:null,finished:null,announcement:'Eyes down! The game is starting.'});}
async function callNext(){if(!state.isHost||state.phase!=='playing'||!state.deck.length)return;const deck=[...state.deck],n=deck.pop(),called=[...state.called,n],updates={deck,called,announcement:callPhrase(n)};if(state.mode==='party'&&state.actions.length&&n%5===0)updates.partyEvent={id:`${Date.now()}-${n}`,number:n,action:state.actions[(n/5-1)%state.actions.length]};await update(state.roomRef,updates);speak(n);tone();if(called.length===90)stopAuto();}
function callPhrase(n){const nick={1:'Kelly’s eye',2:'One little duck',3:'Cup of tea',7:'Lucky seven',11:'Legs eleven',22:'Two little ducks',33:'All the threes',44:'Droopy drawers',55:'Snakes alive',66:'Clickety click',77:'Sunset strip',88:'Two fat ladies',90:'Top of the shop'};return nick[n]?`${nick[n]} — ${n}`:`Number ${n}`;}
async function unlockAudio(){try{if(!state.audioCtx)state.audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(state.audioCtx.state==='suspended')await state.audioCtx.resume();state.audioReady=true;if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance('Sound ready');u.volume=.9;speechSynthesis.speak(u);}toast('Sound ready');}catch{toast('Sound could not start');}}
function speak(n){if(!state.sound||!state.audioReady||!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(callPhrase(n));u.rate=.88;speechSynthesis.cancel();speechSynthesis.speak(u);}
function tone(){if(!state.sound||!state.audioReady||!state.audioCtx)return;try{const o=state.audioCtx.createOscillator(),g=state.audioCtx.createGain();o.frequency.value=660;g.gain.setValueAtTime(.05,state.audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,state.audioCtx.currentTime+.16);o.connect(g).connect(state.audioCtx.destination);o.start();o.stop(state.audioCtx.currentTime+.16);}catch{}}
function showParty(n,a){$('partyChallengeText').textContent=`Number ${n}: ${a}`;$('partyAlert').classList.remove('hidden');setTimeout(()=>$('partyAlert').classList.add('hidden'),9000);showModal('Party number!',`${n} — ${a}. Alcohol is optional; anyone may skip or use a soft drink.`,'🥳');}
function toggleAuto(){if(state.phase!=='playing')return;if(state.autoTimer)stopAuto();else{callNext();state.autoTimer=setInterval(callNext,+$('speedSelect').value);$('autoCallBtn').textContent='Pause Auto';}}
function stopAuto(){clearInterval(state.autoTimer);state.autoTimer=null;if($('autoCallBtn'))$('autoCallBtn').textContent='Start Auto';}

function render(){const online=state.players.filter(p=>p.connected),finished=state.phase==='finished';$('roomCodeDisplay').textContent=state.roomCode||'----';$('gameRoomCode').textContent=state.roomCode||'----';$('playerCount').textContent=`${online.length} player${online.length===1?'':'s'}`;$('modeBadge').textContent=state.mode==='party'?'🥳 Drinking & Dares Bingo':'🎱 Classic Bingo';$('gameModeLabel').textContent=state.mode==='party'?'Party':'Classic';$('playerList').innerHTML=state.players.map(p=>`<div class="player-item"><div class="player-avatar">${p.name?.[0]?.toUpperCase()||'P'}</div><b>${esc(p.name||'Player')}</b><span class="coin-pill">${state.balances[p.id]||0} 🪙</span>${p.creator?'<span class="creator-badge">CREATOR</span>':''}${!p.connected?'<span class="creator-badge">OFFLINE</span>':''}</div>`).join('');$('startGameBtn').classList.toggle('hidden',!state.isHost);$('waitingMessage').classList.toggle('hidden',state.isHost);$('hostControls').classList.toggle('hidden',!state.isHost);$('playerNameDisplay').textContent=state.myName;$('walletBalance').textContent=`${state.balances[state.myId]??state.myLocalCoins} 🪙`;const current=state.called.at(-1);$('currentBall').textContent=current??'—';$('calledCount').textContent=`${state.called.length} / 90`;$('finishedBanner').classList.toggle('hidden',!finished);$('finishedText').textContent=finished?'Full House claimed — this game has finished':'Game finished';document.querySelectorAll('.claim-btn').forEach(b=>b.disabled=finished);$('nextBallBtn').disabled=finished;$('autoCallBtn').disabled=finished;$('announcement').textContent=finished?'Congratulations — Full House!':($('announcement').textContent||'Eyes down!');renderTicket();renderBalls();renderBoard();renderLeaderboard();renderChat();}
function renderTicket(){const t=state.tickets[state.myId];if(!t){$('ticketGrid').innerHTML='';return;}$('ticketGrid').innerHTML='';let marked=0;t.flat().forEach(n=>{const c=document.createElement('button');c.className='ticket-cell';c.type='button';if(!n){c.classList.add('blank');c.disabled=true;}else{c.innerHTML=`<span>${n}</span>`;if(state.marks.has(n)){c.classList.add('called');marked++;}else if(state.called.includes(n))c.classList.add('available');c.onclick=()=>toggleMark(n);}$('ticketGrid').appendChild(c);});$('ticketProgress').textContent=`${marked} marked`;}
function toggleMark(n){if(!state.called.includes(n)){toast('That number has not been called yet.');return;}state.marks.has(n)?state.marks.delete(n):state.marks.add(n);renderTicket();}
function renderBalls(){$('recentBalls').innerHTML=[...state.called].reverse().slice(0,12).map(n=>`<div class="mini-ball">${n}</div>`).join('')||'<span class="status-text">No numbers called yet</span>';}
function renderBoard(){$('numberBoard').innerHTML=Array.from({length:90},(_,i)=>`<div class="board-number ${state.called.includes(i+1)?'called':''}">${i+1}</div>`).join('');}
function renderLeaderboard(){const list=[...state.players].sort((a,b)=>(state.balances[b.id]||0)-(state.balances[a.id]||0));$('leaderboard').innerHTML=list.map((p,i)=>`<div><span>${i+1}. ${esc(p.name||'Player')}</span><b>${state.balances[p.id]||0} 🪙</b></div>`).join('');}
function renderChat(){const html=state.chat.length?state.chat.map(m=>`<div class="chat-message ${m.playerId===state.myId?'mine':''}"><div class="chat-meta"><strong>${esc(m.name||'Player')}</strong><span>${new Date(m.createdAt||Date.now()).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</span></div><div class="chat-body">${esc(m.text||'')}</div></div>`).join(''):'<div class="chat-empty">No messages yet</div>';['chatMessages','chatMessagesGame'].forEach(id=>{const box=$(id);if(box){box.innerHTML=html;box.scrollTop=box.scrollHeight;}});}
async function sendChat(input){const text=cleanMessage(input.value);if(!text||!state.roomCode)return;input.value='';const chatRef=ref(db,`rooms/${state.roomCode}/chat`);await push(chatRef,{playerId:state.myId,name:state.myName,text,createdAt:Date.now()});const snap=await get(chatRef),entries=Object.entries(snap.val()||{}).sort((a,b)=>(a[1].createdAt||0)-(b[1].createdAt||0));for(const [key] of entries.slice(0,Math.max(0,entries.length-50)))await remove(ref(db,`rooms/${state.roomCode}/chat/${key}`));}

async function claim(type){if(state.phase!=='playing')return;if(state.isHost)await validateClaim(state.myId,type);else await push(ref(db,`rooms/${state.roomCode}/claims`),{playerId:state.myId,type,createdAt:Date.now()});}
async function validateClaim(id,type){if(state.phase!=='playing')return;const t=state.tickets[id],p=state.players.find(x=>x.id===id);if(!t||!p)return;const prior=state.wins[id]||[];if(prior.includes(type)){await publishNotice(id,'Already claimed','You have already collected that prize.','🙈');return;}const rows=t.filter(r=>r.filter(Boolean).every(n=>state.called.includes(n))).length,total=t.flat().filter(Boolean).every(n=>state.called.includes(n)),valid=(type==='line'&&rows>=1)||(type==='two-lines'&&rows>=2)||(type==='full-house'&&total);if(!valid){await publishNotice(id,'Not quite yet','Some required numbers have not been called. Keep playing!','🙈');return;}const coins=state.prizes[type]||0,label=type==='line'?'a line':type==='two-lines'?'two lines':'FULL HOUSE',balance=(state.balances[id]||0)+coins,wins={...state.wins,[id]:[...prior,type]},balances={...state.balances,[id]:balance},msg=`${p.name} won ${label} and ${coins} Skinners Coins!`;if(id===state.myId){state.myLocalCoins=balance;localStorage.setItem('skinnersCoins',String(balance));}const payload={wins,balances,notice:{id:`${Date.now()}-${id}`,target:null,title:type==='full-house'?'Congratulations!':'We have a winner!',message:msg,emoji:'🏆'}};if(type==='full-house'){stopAuto();payload.phase='finished';payload.finished={id:`${Date.now()}-${id}`,winnerId:id,winnerName:p.name,finishedAt:Date.now()};payload.announcement=`Congratulations ${p.name} — Full House!`;payload.deck=[];}await update(state.roomRef,payload);}
async function publishNotice(target,title,message,emoji){await set(ref(db,`rooms/${state.roomCode}/notice`),{id:`${Date.now()}-${target}`,target,title,message,emoji});}
function attachClaimListener(){state.claimUnsub?.();if(!state.isHost||!state.roomCode)return;state.claimUnsub=onValue(ref(db,`rooms/${state.roomCode}/claims`),async snap=>{for(const [key,c] of Object.entries(snap.val()||{})){await validateClaim(c.playerId,c.type);await remove(ref(db,`rooms/${state.roomCode}/claims/${key}`));}});}

function showModal(t,m,e){$('modalTitle').textContent=t;$('modalMessage').textContent=m;$('modalEmoji').textContent=e;$('modal').classList.remove('hidden');}
async function leave(){stopAuto();state.unsubscribe?.();state.claimUnsub?.();if(state.roomCode)await update(playerPath(state.roomCode,state.myId),{connected:false,lastSeen:Date.now()}).catch(()=>{});location.reload();}
onValue(ref(db,'.info/connected'),snap=>{if(snap.val()&&state.roomCode)update(playerPath(state.roomCode,state.myId),{connected:true,lastSeen:Date.now()}).catch(()=>{});});

document.addEventListener('pointerdown',()=>{if(!state.audioReady)unlockAudio();},{once:true});
$('createGameBtn').onclick=()=>{$('createPanel').classList.toggle('hidden');$('joinPanel').classList.add('hidden');};$('showJoinBtn').onclick=()=>{$('joinPanel').classList.toggle('hidden');$('createPanel').classList.add('hidden');};$('gameMode').onchange=()=>$('partySetup').classList.toggle('hidden',$('gameMode').value!=='party');$('confirmCreateBtn').onclick=createGame;$('joinGameBtn').onclick=joinGame;$('startGameBtn').onclick=startGame;$('copyCodeBtn').onclick=async()=>{await navigator.clipboard?.writeText(state.roomCode);toast('Room code copied');};$('leaveLobbyBtn').onclick=leave;$('nextBallBtn').onclick=callNext;$('autoCallBtn').onclick=toggleAuto;$('speedSelect').onchange=()=>{if(state.autoTimer){stopAuto();toggleAuto();}};$('newRoundBtn').onclick=startGame;$('toggleBoardBtn').onclick=()=>{const h=$('numberBoard').classList.toggle('hidden');$('toggleBoardBtn').textContent=h?'Show board':'Hide board';};document.querySelectorAll('.claim-btn').forEach(b=>b.onclick=()=>claim(b.dataset.claim));$('modalCloseBtn').onclick=()=>$('modal').classList.add('hidden');$('soundBtn').onclick=async()=>{state.sound=!state.sound;$('soundBtn').textContent=state.sound?'🔊':'🔇';if(state.sound)await unlockAudio();else toast('Sound off');};$('roomCodeInput').oninput=e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,4);$('chatForm').onsubmit=e=>{e.preventDefault();sendChat($('chatInput'));};$('chatFormGame').onsubmit=e=>{e.preventDefault();sendChat($('chatInputGame'));};renderBoard();