const API='https://skinners-bar-bingo-default-rtdb.europe-west1.firebasedatabase.app/cardGames/battleships';
const playerId=localStorage.getItem('skinnersPlayerId')||crypto.randomUUID();localStorage.setItem('skinnersPlayerId',playerId);
const $=id=>document.getElementById(id);let mode='',room='',state={},poll=null,myKey='',botBusy=false;
const fleet=[4,3,3,2,2],size=8,clean=s=>(s||'Captain').trim().replace(/[<>]/g,'').slice(0,18)||'Captain';
const getRoom=async c=>(await fetch(`${API}/${c}.json`)).json();
const putRoom=async data=>fetch(`${API}/${room}.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
const patch=async data=>fetch(`${API}/${room}.json`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function randomBoard(){const ships=[];for(const len of fleet){let cells;do{const horizontal=Math.random()<.5,r=Math.floor(Math.random()*(horizontal?size:size-len+1)),c=Math.floor(Math.random()*(horizontal?size-len+1:size));cells=Array.from({length:len},(_,i)=>horizontal?r*size+c+i:(r+i)*size+c)}while(ships.some(s=>s.cells.some(x=>cells.includes(x))));ships.push({cells,hits:[]})}return{ships,shots:[]}}
function allSunk(board){return board.ships.every(s=>s.cells.every(c=>s.hits.includes(c)))}
function remaining(board){return board.ships.filter(s=>!s.cells.every(c=>s.hits.includes(c))).length}
function fire(board,index){if(board.shots.includes(index))return null;board.shots.push(index);const ship=board.ships.find(s=>s.cells.includes(index));if(ship)ship.hits.push(index);return{hit:!!ship,sunk:ship?ship.cells.every(c=>ship.hits.includes(c)):false}}
async function reserve(){for(let i=0;i<30;i++){const c=String(Math.floor(1000+Math.random()*9000));if(!await getRoom(c))return c}throw Error('Could not create a room.')}
async function startSingle(){mode='single';room='SOLO';myKey='p1';const name=clean($('name').value);state={phase:'playing',turn:'p1',players:{p1:{id:playerId,name,board:randomBoard()},p2:{id:'bot',name:'Admiral Bot',board:randomBoard()}},winner:''};showGame();render()}
async function createMulti(){try{$('setupStatus').textContent='Creating room…';mode='multi';room=await reserve();myKey='p1';const name=clean($('name').value);state={phase:'lobby',turn:'p1',players:{p1:{id:playerId,name,board:randomBoard()}},winner:''};await putRoom(state);$('setup').classList.add('hidden');$('lobby').classList.remove('hidden');startPolling()}catch(e){$('setupStatus').textContent=e.message}}
async function joinMulti(){try{room=$('codeInput').value.trim();if(!/^\d{4}$/.test(room))throw Error('Enter a valid four-digit code.');const current=await getRoom(room);if(!current)throw Error('Room not found.');if(current.players?.p2)throw Error('This battle is full.');mode='multi';myKey='p2';current.players.p2={id:playerId,name:clean($('name').value),board:randomBoard()};current.phase='playing';state=current;await putRoom(current);$('setup').classList.add('hidden');showGame();startPolling()}catch(e){$('setupStatus').textContent=e.message}}
function startPolling(){clearInterval(poll);const read=async()=>{const data=await getRoom(room);if(!data)return;state=data;const entry=Object.entries(state.players||{}).find(([,p])=>p.id===playerId);if(entry)myKey=entry[0];if(state.phase==='playing'||state.phase==='finished')showGame();else renderLobby();render()};read();poll=setInterval(read,700)}
function renderLobby(){$('roomCode').textContent=room;$('lobbyText').textContent=state.players?.p2?'Enemy captain joined!':'Waiting for another captain…';$('playersList').innerHTML=Object.values(state.players||{}).map(p=>`<div class="player-chip"><strong>${p.name}</strong><span>Ready ⚓</span></div>`).join('')}
function showGame(){$('setup').classList.add('hidden');$('lobby').classList.add('hidden');$('game').classList.remove('hidden')}
function buildBoard(el,board,enemy){el.innerHTML='';for(let i=0;i<size*size;i++){const b=document.createElement('button');b.className='cell';b.type='button';const shot=board.shots.includes(i),ship=board.ships.find(s=>s.cells.includes(i));if(!enemy&&ship)b.classList.add('ship');if(shot){b.classList.add('shot',ship?'hit':'miss');if(ship&&ship.cells.every(c=>ship.hits.includes(c)))b.classList.add('sunk')}if(enemy&&!shot)b.onclick=()=>shoot(i);el.appendChild(b)}}
async function shoot(index){if(state.phase!=='playing'||state.turn!==myKey)return;const enemyKey=myKey==='p1'?'p2':'p1',enemy=structuredClone(state.players[enemyKey].board),result=fire(enemy,index);if(!result)return;state.players[enemyKey].board=enemy;if(allSunk(enemy)){state.phase='finished';state.winner=myKey}else state.turn=enemyKey;if(mode==='multi')await patch({phase:state.phase,turn:state.turn,winner:state.winner||'',[`players/${enemyKey}/board`]:enemy});render();if(mode==='single'&&state.phase==='playing')setTimeout(botTurn,650)}
function botTurn(){if(botBusy||state.turn!=='p2'||state.phase!=='playing')return;botBusy=true;const board=state.players.p1.board;const choices=[];for(let i=0;i<size*size;i++)if(!board.shots.includes(i))choices.push(i);fire(board,choices[Math.floor(Math.random()*choices.length)]);state.players.p1.board=board;if(allSunk(board)){state.phase='finished';state.winner='p2'}else state.turn='p1';botBusy=false;render()}
function render(){if(!state.players?.[myKey])return;const enemyKey=myKey==='p1'?'p2':'p1',me=state.players[myKey],enemy=state.players[enemyKey];if(!enemy){renderLobby();return}$('hudRoom').textContent=mode==='single'?'SOLO':room;$('myName').textContent=me.name;$('enemyName').textContent=enemy.name;$('myShips').textContent=`${remaining(me.board)} ships`;$('enemyShips').textContent=`${remaining(enemy.board)} ships`;buildBoard($('myBoard'),me.board,false);buildBoard($('enemyBoard'),enemy.board,true);const mine=state.turn===myKey;$('turnText').textContent=state.phase==='finished'?'Battle finished':mine?'Your turn':'Enemy turn';$('message').textContent=state.phase==='finished'?'The battle is over.':mine?'Tap an enemy square to fire.':'Waiting for enemy fire…';if(state.phase==='finished'){const won=state.winner===myKey;$('winnerTitle').textContent=won?'Victory!':'Fleet Destroyed';$('winnerText').textContent=won?'You sank every enemy ship.':`${enemy.name} won the battle.`;$('winner').classList.remove('hidden')}}
$('single').onclick=startSingle;$('create').onclick=createMulti;$('join').onclick=joinMulti;$('copyCode').onclick=async()=>{await navigator.clipboard.writeText(room);$('copyCode').textContent='Copied!';setTimeout(()=>$('copyCode').textContent='Copy Code',1200)};$('playAgain').onclick=()=>location.reload();