const API='https://skinners-bar-bingo-default-rtdb.europe-west1.firebasedatabase.app/cardGames/battleships';
const playerId=localStorage.getItem('skinnersPlayerId')||crypto.randomUUID();
localStorage.setItem('skinnersPlayerId',playerId);
const $=id=>document.getElementById(id);
let mode='',room='',state={},poll=null,myKey='',botBusy=false,selectedShip=0;
const fleet=[4,3,3,2,2],size=8,clean=s=>(s||'Captain').trim().replace(/[<>]/g,'').slice(0,18)||'Captain';
const shipNames=['Battleship','Cruiser 1','Cruiser 2','Patrol 1','Patrol 2'];
const getRoom=async c=>(await fetch(`${API}/${c}.json`)).json();
const putRoom=async data=>fetch(`${API}/${room}.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
const patch=async data=>fetch(`${API}/${room}.json`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function randomBoard(){const ships=[];for(const len of fleet){let cells,horizontal;do{horizontal=Math.random()<.5;const r=Math.floor(Math.random()*(horizontal?size:size-len+1));const c=Math.floor(Math.random()*(horizontal?size-len+1:size));cells=Array.from({length:len},(_,i)=>horizontal?r*size+c+i:(r+i)*size+c)}while(ships.some(s=>s.cells.some(x=>cells.includes(x))));ships.push({cells,hits:[],horizontal})}return{ships,shots:[]}}
function allSunk(board){return board.ships.every(s=>s.cells.every(c=>s.hits.includes(c)))}
function remaining(board){return board.ships.filter(s=>!s.cells.every(c=>s.hits.includes(c))).length}
function fire(board,index){if(board.shots.includes(index))return null;board.shots.push(index);const ship=board.ships.find(s=>s.cells.includes(index));if(ship&&!ship.hits.includes(index))ship.hits.push(index);return{hit:!!ship,sunk:ship?ship.cells.every(c=>ship.hits.includes(c)):false,shipIndex:ship?board.ships.indexOf(ship):-1}}
async function reserve(){for(let i=0;i<30;i++){const c=String(Math.floor(1000+Math.random()*9000));if(!await getRoom(c))return c}throw Error('Could not create a room.')}
function placementPlayer(name,id=playerId){return{id,name,board:randomBoard(),ready:false}}
async function startSingle(){mode='single';room='SOLO';myKey='p1';state={phase:'placement',turn:'p1',players:{p1:placementPlayer(clean($('name').value)),p2:{...placementPlayer('Admiral Bot','bot'),ready:true}},winner:'',lastEvent:''};showGame();render()}
async function createMulti(){try{$('setupStatus').textContent='Creating room…';mode='multi';room=await reserve();myKey='p1';state={phase:'placement',turn:'p1',players:{p1:placementPlayer(clean($('name').value))},winner:'',lastEvent:''};await putRoom(state);$('setup').classList.add('hidden');showGame();startPolling()}catch(e){$('setupStatus').textContent=e.message}}
async function joinMulti(){try{room=$('codeInput').value.trim();if(!/^\d{4}$/.test(room))throw Error('Enter a valid four-digit code.');const current=await getRoom(room);if(!current)throw Error('Room not found.');if(current.players?.p2)throw Error('This battle is full.');mode='multi';myKey='p2';current.players.p2=placementPlayer(clean($('name').value));current.phase='placement';current.lastEvent='';state=current;await putRoom(current);$('setup').classList.add('hidden');showGame();startPolling()}catch(e){$('setupStatus').textContent=e.message}}
function startPolling(){clearInterval(poll);const read=async()=>{const data=await getRoom(room);if(!data)return;state=data;const entry=Object.entries(state.players||{}).find(([,p])=>p.id===playerId);if(entry)myKey=entry[0];showGame();render()};read();poll=setInterval(read,700)}
function showGame(){$('setup').classList.add('hidden');$('lobby').classList.add('hidden');$('game').classList.remove('hidden')}
function shipAt(board,index){return board.ships.findIndex(s=>s.cells.includes(index))}
function candidateCells(start,len,horizontal){const r=Math.floor(start/size),c=start%size;if(horizontal&&c+len>size)return null;if(!horizontal&&r+len>size)return null;return Array.from({length:len},(_,i)=>horizontal?start+i:start+i*size)}
function moveSelected(start,rotate=false){const me=state.players?.[myKey];if(!me||state.phase!=='placement'||me.ready)return;const ship=me.board.ships[selectedShip];if(!ship)return;const horizontal=rotate?!ship.horizontal:ship.horizontal;const cells=candidateCells(start,ship.cells.length,horizontal);if(!cells)return flash('That ship would go off the board.');const blocked=me.board.ships.some((s,i)=>i!==selectedShip&&s.cells.some(c=>cells.includes(c)));if(blocked)return flash('Ships cannot overlap.');ship.cells=cells;ship.horizontal=horizontal;ship.hits=[];me.board.shots=[];savePlacement();render()}
function flash(text){$('message').textContent=text;setTimeout(render,1100)}
async function savePlacement(){if(mode==='multi')await patch({[`players/${myKey}/board`]:state.players[myKey].board})}
async function rotateSelected(){const ship=state.players?.[myKey]?.board?.ships?.[selectedShip];if(ship)moveSelected(ship.cells[0],true)}
async function randomise(){const me=state.players?.[myKey];if(!me||me.ready)return;me.board=randomBoard();selectedShip=0;await savePlacement();render()}
async function readyFleet(){const me=state.players?.[myKey];if(!me||me.ready)return;me.ready=true;if(mode==='single'){state.phase='playing';state.turn='p1';state.lastEvent='Battle started — fire when ready!';render();return}await patch({[`players/${myKey}/ready`]:true});const latest=await getRoom(room);state=latest;const ps=Object.values(state.players||{});if(ps.length===2&&ps.every(p=>p.ready)){state.phase='playing';state.turn='p1';state.lastEvent='Both fleets are ready. Battle stations!';await patch({phase:'playing',turn:'p1',lastEvent:state.lastEvent})}render()}
function buildBoard(board,view){const el=$('mainBoard');el.innerHTML='';el.classList.toggle('targeting',view==='enemy'&&state.phase==='playing'&&state.turn===myKey);for(let i=0;i<size*size;i++){const b=document.createElement('button');b.className='cell';b.type='button';const shot=board.shots.includes(i),shipIndex=shipAt(board,i),ship=shipIndex>=0?board.ships[shipIndex]:null,sunk=ship&&ship.cells.every(c=>ship.hits.includes(c));const showShip=view==='own'||sunk;if(showShip&&ship)b.classList.add('ship');if(view==='own'&&state.phase==='placement'&&shipIndex===selectedShip)b.classList.add('selected');if(shot)b.classList.add('shot',ship?'hit':'miss');if(sunk)b.classList.add('sunk');if(state.phase==='placement'&&view==='own'&&!state.players[myKey].ready){b.onclick=()=>{if(shipIndex>=0){selectedShip=shipIndex;render()}else moveSelected(i)}}else if(view==='enemy'&&state.phase==='playing'&&state.turn===myKey&&!shot)b.onclick=()=>shoot(i);el.appendChild(b)}}
function fleetStatus(board,enemyView=false){$('fleetStatus').innerHTML=board.ships.map((s,i)=>{const sunk=s.cells.every(c=>s.hits.includes(c));return`<div class="fleet-chip ${sunk?'sunk':''} ${!enemyView&&state.phase==='placement'&&i===selectedShip?'selected':''}"><strong>${s.cells.length} long</strong>${sunk?'Sunk':shipNames[i]}</div>`}).join('')}
async function shoot(index){if(state.phase!=='playing'||state.turn!==myKey)return;const enemyKey=myKey==='p1'?'p2':'p1',enemy=structuredClone(state.players[enemyKey].board),result=fire(enemy,index);if(!result)return;state.players[enemyKey].board=enemy;const sunkName=result.shipIndex>=0?shipNames[result.shipIndex]:'ship';state.lastEvent=result.sunk?`🚢 You sank ${state.players[enemyKey].name}'s ${sunkName}!`:result.hit?'💥 Direct hit!':'💦 Miss!';if(allSunk(enemy)){state.phase='finished';state.winner=myKey}else state.turn=enemyKey;if(mode==='multi')await patch({phase:state.phase,turn:state.turn,winner:state.winner||'',lastEvent:state.lastEvent,[`players/${enemyKey}/board`]:enemy});render();if(mode==='single'&&state.phase==='playing')setTimeout(botTurn,650)}
function botTurn(){if(botBusy||state.turn!=='p2'||state.phase!=='playing')return;botBusy=true;const board=state.players.p1.board,choices=[];for(let i=0;i<size*size;i++)if(!board.shots.includes(i))choices.push(i);const result=fire(board,choices[Math.floor(Math.random()*choices.length)]),name=result.shipIndex>=0?shipNames[result.shipIndex]:'ship';state.players.p1.board=board;state.lastEvent=result.sunk?`🚢 Admiral Bot sank your ${name}!`:result.hit?'💥 Admiral Bot scored a hit!':'💦 Admiral Bot missed.';if(allSunk(board)){state.phase='finished';state.winner='p2'}else state.turn='p1';botBusy=false;render()}
function render(){const me=state.players?.[myKey];if(!me)return;const enemyKey=myKey==='p1'?'p2':'p1',enemy=state.players?.[enemyKey];$('hudRoom').textContent=mode==='single'?'SOLO':room;$('placementTools').classList.toggle('hidden',state.phase!=='placement'||me.ready);let view='own';if(state.phase==='playing'||state.phase==='finished')view=state.turn===myKey||state.phase==='finished'?'enemy':'own';if(!enemy)view='own';const board=view==='enemy'?enemy.board:me.board;const title=view==='enemy'?(enemy?.name||'Enemy Fleet'):me.name;$('boardEyebrow').textContent=view==='enemy'?'ENEMY WATERS':'YOUR WATERS';$('boardTitle').textContent=title;$('shipsLeft').textContent=`${remaining(board)} ships`;buildBoard(board,view);fleetStatus(board,view==='enemy');if(state.phase==='placement'){$('turnText').textContent=me.ready?'Fleet ready':'Place your fleet';$('message').textContent=me.ready?(enemy?'Waiting for the other captain…':'Waiting for another captain to join…'):'Tap a ship, then tap an empty square to move it.'}else{const mine=state.turn===myKey;$('turnText').textContent=state.phase==='finished'?'Battle finished':mine?'Your turn':'Enemy turn';$('message').textContent=state.lastEvent||(mine?'Tap an enemy square to fire.':'Your fleet is under attack…')}if(mode==='multi'&&state.phase==='placement'&&!enemy){$('message').textContent=me.ready?'Fleet ready — waiting for another captain.':'Place your fleet while waiting for another captain.'}$('message').classList.toggle('sunk-alert',/sank|sunk/i.test(state.lastEvent||''));if(state.phase==='finished'){const won=state.winner===myKey;$('winnerTitle').textContent=won?'Victory!':'Fleet Destroyed';$('winnerText').textContent=won?'You sank every enemy ship.':`${enemy.name} won the battle.`;$('winner').classList.remove('hidden')}}
$('single').onclick=startSingle;$('create').onclick=createMulti;$('join').onclick=joinMulti;$('rotateShip').onclick=rotateSelected;$('randomiseShips').onclick=randomise;$('readyShips').onclick=readyFleet;$('copyCode').onclick=async()=>{await navigator.clipboard.writeText(room);$('copyCode').textContent='Copied!';setTimeout(()=>$('copyCode').textContent='Copy Code',1200)};$('playAgain').onclick=()=>location.reload();